exclude: ['README.md']
permalink: pretty

collections:
  case-study:
    output: true
    permalink: /en/case-study/:path/
  case-study_es:
    output: true
    permalink: /es/estudo/:path/
  case-study_pt:
    output: true
    permalink: /pt/caso/:path/
